from os import getenv


class colors:
    """
    https://ru.wikipedia.org/wiki/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D1%8E%D1%89%D0%B8%D0%B5_%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D0%B8_ANSI#CSI_%D0%BA%D0%BE%D0%B4%D1%8B
    """

    def __init__(self):
        if getenv('ANSI_COLORS_DISABLED') is None:
            self.RESET = '\033[0m'
            self.BOLD = '\033[1m'
            self.ITALIC = '\033[3m'
            self.UNDERL = '\033[4m'
            self.REVERSE = '\033[7m'
            self.CROSSL = '\033[9m'
            self.C_BLACK = '\033[30m'
            self.C_LRED = '\033[31m'
            self.C_LGREEN = '\033[32m'
            self.C_BROWN = '\033[33m'
            self.C_LBLUE = '\033[34m'
            self.C_LMAGENTA = '\033[35m'
            self.C_LCYAN = '\033[36m'
            self.C_LGREY = '\033[37m'
            self.C_GREY = '\033[90m'
            self.C_RED = '\033[91m'
            self.C_GREEN = '\033[92m'
            self.C_YELLOW = '\033[93m'
            self.C_BLUE = '\033[94m'
            self.C_MAGENTA = '\033[95m'
            self.C_CYAN = '\033[96m'
            self.C_WHITE = '\033[97m'
            self.H_BLACK = '\033[40m'
            self.H_LRED = '\033[41m'
            self.H_LGREEN = '\033[42m'
            self.H_BROWN = '\033[43m'
            self.H_LBLUE = '\033[44m'
            self.H_LMAGENTA = '\033[45m'
            self.H_LCYAN = '\033[46m'
            self.H_LGREY = '\033[47m'
            self.H_GREY = '\033[100m'
            self.H_RED = '\033[101m'
            self.H_GREEN = '\033[102m'
            self.H_YELLOW = '\033[103m'
            self.H_BLUE = '\033[104m'
            self.H_MAGENTA = '\033[105m'
            self.H_CYAN = '\033[106m'
            self.H_WHITE = '\033[107m'
        else:
            self.RESET = ''
            self.BOLD = ''
            self.ITALIC = ''
            self.UNDERL = ''
            self.REVERSE = ''
            self.CROSSL = ''
            self.C_BLACK = ''
            self.C_LRED = ''
            self.C_LGREEN = ''
            self.C_BROWN = ''
            self.C_LBLUE = ''
            self.C_LMAGENTA = ''
            self.C_LCYAN = ''
            self.C_LGREY = ''
            self.C_GREY = ''
            self.C_RED = ''
            self.C_GREEN = ''
            self.C_YELLOW = ''
            self.C_BLUE = ''
            self.C_MAGENTA = ''
            self.C_CYAN = ''
            self.C_WHITE = ''
            self.H_BLACK = ''
            self.H_LRED = ''
            self.H_LGREEN = ''
            self.H_BROWN = ''
            self.H_LBLUE = ''
            self.H_LMAGENTA = ''
            self.H_LCYAN = ''
            self.H_LGREY = ''
            self.H_GREY = ''
            self.H_RED = ''
            self.H_GREEN = ''
            self.H_YELLOW = ''
            self.H_BLUE = ''
            self.H_MAGENTA = ''
            self.H_CYAN = ''
            self.H_WHITE = ''


if __name__ == '__main__':
    text_color = colors()
    print(f'{text_color.C_BLUE}{text_color.H_GREY}{text_color.BOLD}Hello{text_color.H_YELLOW} world {text_color.RESET}!!!')